CRITICAL - 2021-06-16 17:43:18 --> session_regenerate_id(): Session ID cannot be regenerated when there is no active session
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'session_regener...', 'C:\\xampp\\htdocs...', 297)
#1 C:\xampp\htdocs\ci4app\system\Session\Session.php(297): session_regenerate_id(true)
#2 C:\xampp\htdocs\ci4app\app\Controllers\Admin\Users.php(29): CodeIgniter\Session\Session->stop()
#3 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->logout()
#4 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#5 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2021-06-16 19:25:42 --> require is not a valid rule.
#0 C:\xampp\htdocs\ci4app\system\Validation\Validation.php(321): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('require')
#1 C:\xampp\htdocs\ci4app\system\Validation\Validation.php(159): CodeIgniter\Validation\Validation->processRules('email', 'email', '', Array, Array)
#2 C:\xampp\htdocs\ci4app\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#3 C:\xampp\htdocs\ci4app\app\Controllers\Admin\Users.php(45): CodeIgniter\Controller->validate(Array)
#4 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#5 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#6 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2021-06-16 19:28:51 --> require is not a valid rule.
#0 C:\xampp\htdocs\ci4app\system\Validation\Validation.php(321): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('require')
#1 C:\xampp\htdocs\ci4app\system\Validation\Validation.php(159): CodeIgniter\Validation\Validation->processRules('email', 'email', 'fikri_erha@gmai...', Array, Array)
#2 C:\xampp\htdocs\ci4app\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#3 C:\xampp\htdocs\ci4app\app\Controllers\Admin\Users.php(45): CodeIgniter\Controller->validate(Array)
#4 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#5 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#6 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2021-06-16 19:29:32 --> require is not a valid rule.
#0 C:\xampp\htdocs\ci4app\system\Validation\Validation.php(321): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('require')
#1 C:\xampp\htdocs\ci4app\system\Validation\Validation.php(159): CodeIgniter\Validation\Validation->processRules('email', 'email', '', Array, Array)
#2 C:\xampp\htdocs\ci4app\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#3 C:\xampp\htdocs\ci4app\app\Controllers\Admin\Users.php(45): CodeIgniter\Controller->validate(Array)
#4 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#5 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#6 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2021-06-16 19:30:29 --> require is not a valid rule.
#0 C:\xampp\htdocs\ci4app\system\Validation\Validation.php(321): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('require')
#1 C:\xampp\htdocs\ci4app\system\Validation\Validation.php(159): CodeIgniter\Validation\Validation->processRules('email', 'email', '', Array, Array)
#2 C:\xampp\htdocs\ci4app\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#3 C:\xampp\htdocs\ci4app\app\Controllers\Admin\Users.php(45): CodeIgniter\Controller->validate(Array)
#4 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#5 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#6 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2021-06-16 19:33:20 --> require is not a valid rule.
#0 C:\xampp\htdocs\ci4app\system\Validation\Validation.php(321): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('require')
#1 C:\xampp\htdocs\ci4app\system\Validation\Validation.php(159): CodeIgniter\Validation\Validation->processRules('email', 'email', '', Array, Array)
#2 C:\xampp\htdocs\ci4app\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#3 C:\xampp\htdocs\ci4app\app\Controllers\Admin\Users.php(45): CodeIgniter\Controller->validate(Array)
#4 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#5 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#6 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2021-06-16 19:39:36 --> Undefined array key 0
#0 C:\xampp\htdocs\ci4app\app\Controllers\Admin\Users.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 52)
#1 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#2 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#3 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-06-16 19:40:35 --> Undefined array key 0
#0 C:\xampp\htdocs\ci4app\app\Controllers\Admin\Users.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 52)
#1 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#2 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#3 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-06-16 19:40:51 --> Undefined array key 0
#0 C:\xampp\htdocs\ci4app\app\Controllers\Admin\Users.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 52)
#1 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#2 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#3 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-06-16 19:41:25 --> Undefined array key 0
#0 C:\xampp\htdocs\ci4app\app\Controllers\Admin\Users.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 52)
#1 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#2 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#3 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-06-16 19:42:54 --> Undefined array key 0
#0 C:\xampp\htdocs\ci4app\app\Controllers\Admin\Users.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 52)
#1 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#2 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#3 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-06-16 19:53:43 --> Undefined property: App\Controllers\Admin\Users::$load
#0 C:\xampp\htdocs\ci4app\app\Controllers\Admin\Users.php(73): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 73)
#1 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#2 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#3 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-06-16 19:55:37 --> Namespace declaration statement has to be the very first statement or after any declare call in the script
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-06-16 19:58:46 --> Undefined constant "App\Controllers\Admin\port_smtp"
#0 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#1 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#2 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2021-06-16 19:59:27 --> Undefined property: App\Controllers\Admin\Users::$load
#0 C:\xampp\htdocs\ci4app\app\Controllers\Admin\Users.php(73): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 73)
#1 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#2 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#3 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-06-16 20:02:18 --> Undefined property: App\Controllers\Admin\Users::$load
#0 C:\xampp\htdocs\ci4app\app\Controllers\Admin\Users.php(73): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 73)
#1 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#2 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#3 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
ERROR - 2021-06-16 20:28:40 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
CRITICAL - 2021-06-16 20:58:59 --> Call to undefined method CodeIgniter\Email\Email::print_debugger()
#0 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#1 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#2 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2021-06-16 20:59:39 --> Call to undefined method CodeIgniter\Email\Email::hasError()
#0 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#1 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#2 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2021-06-16 21:08:26 --> Undefined property: App\Controllers\Admin\Users::$load
#0 C:\xampp\htdocs\ci4app\app\Controllers\Admin\Users.php(71): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 71)
#1 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#2 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#3 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-06-16 21:13:03 --> Call to undefined function App\Controllers\Admin\printDebugger()
#0 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#1 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#2 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#5 {main}
ERROR - 2021-06-16 21:14:52 --> Email: sendWithSmtp throwed fsockopen(): php_network_getaddresses: getaddrinfo failed: A non-recoverable error occurred during a database lookup. 
ERROR - 2021-06-16 21:18:23 --> Email: sendWithSmtp throwed fsockopen(): php_network_getaddresses: getaddrinfo failed: A non-recoverable error occurred during a database lookup. 
ERROR - 2021-06-16 21:19:48 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-06-16 21:19:50 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-06-16 21:19:52 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-06-16 21:19:54 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-06-16 21:19:56 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-06-16 21:19:58 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-06-16 21:20:00 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-06-16 21:20:02 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-06-16 21:20:05 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-06-16 21:20:07 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-06-16 21:20:16 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
CRITICAL - 2021-06-16 21:23:20 --> Call to undefined method CodeIgniter\Email\Email::set_newline()
#0 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#1 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#2 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2021-06-16 21:25:59 --> Call to undefined method CodeIgniter\Email\Email::newline()
#0 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#1 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#2 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#5 {main}
ERROR - 2021-06-16 21:26:25 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
CRITICAL - 2021-06-16 21:35:44 --> Undefined property: App\Controllers\Admin\Users::$load
#0 C:\xampp\htdocs\ci4app\app\Controllers\Admin\Users.php(58): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 58)
#1 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(928): App\Controllers\Admin\Users->confirm()
#2 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Users))
#3 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4app\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
